name: Deploy para GitHub pages 

on:
  push:
    branches:
      - main # Executa quando há mudanças na branch principal

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout do repositório
        uses: actions/checkout@v4

      - name: configurar GitHub pages
        uses: actions/configure-pages@v5

      - name: Criar artefato para deploy
        uses: actions/upload-pages-artifact@v3 # pode tentar também @v2 se funcionar
        with:
          path: .

      - name: Publicar no GitHub pages
        uses: actions/deploy-pages@v4

    


    
